apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-wordpress
  namespace: mysql
  labels:
    database: ""
    type: mysql
    db: mysql-wp
data:
  mysql.cnf: |
    [mysqld]
    max_allowed_packet = 268435456