apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-wordpress
  namespace: mysql
  labels:
    database: ""
    type: mysql
    db: mysql-wp
spec:
  capacity:
    storage: 5G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain