apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-wordpress
  namespace: mysql
  labels:
    database: ""
    type: mysql
    db: mysql-wp
spec:
  resources:
    requests:
      storage: 5G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: mysql-wordpress