fullnameOverride: traefik
image:
  name: traefik
  tag: 2.10.3
  pullPolicy: IfNotPresent

env:
  - name: CERTRESOLVER_EMAIL_ADDRESS
    valueFrom:
      secretKeyRef:
        name: traefik
        key: CERTRESOLVER_EMAIL_ADDRESS

additionalArguments:
  #- --serversTransport.insecureSkipVerify=true
  - --api.insecure=true

certResolver:
  letsencrypt:
    email: $(CERTRESOLVER_EMAIL_ADDRESS)
    tlsChallenge: true
    storage: /data/acme.json

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: false
    allowExternalNameServices: false
    allowEmptyServices: false
    namespaces: []
  kubernetesIngress:
    enabled: false

persistence:
  enabled: true
  size: 1Gi
  path: /data

ports:
  web:
    port: 8000
    exposedPort: 80
    expose: true
    protocol: TCP
  websecure:
    port: 4443
    exposedPort: 443
    expose: true
    protocol: TCP
    appProtocol: https

services:
  enabled: true
  single: true
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local

resources:
  limits:
    memory: "200Mi"
  requests:
    cpu: "50m"
    memory: "100Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.35
      command: ["sh", "-c", "touch /cert/acme.json && chmod -Rv 600 /data/* && chown 65532:65532 /data/acme.json"]
      volumeMounts:
        - name: data
          mountPath: /cert

#* --- Metrics and Logs
metrics:
  prometheus: null

logs:
  general:
    level: INFO
  access:
    enabled: true